apiVersion: apps/v1
kind: Deployment
metadata:
  name: isadri-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isadri-app
  template:
    metadata:
      labels:
        app: isadri-app
    spec:
      containers:
        - name: app
          image: isadri/iot-app:v1
          ports:
            - containerPort: 8888

